Error Patterns front end
googleinterns/inventory-visualizer pull request #25
Opened 2020-09-25 14:53 UTC by sophiebpeneva

2020-09-28 16:46 UTC, peterborocz requested changes

2020-09-28 16:46 UTC, peterborocz commented on frontend/src/app/api.service.ts
> +   * @description This method makes an http call and fetches data that contais information about
Typo: contains

2020-09-28 16:46 UTC, peterborocz commented on frontend/src/app/api.service.ts
> +   * @param string filename2 The name of the second file with the comaprison data
Typo: comparison

2020-09-29 12:25 UTC, sophiebpeneva commented on frontend/src/app/api.service.ts
> +   * @param string filename2 The name of the second file with the comaprison data
done

2020-09-29 12:25 UTC, sophiebpeneva commented on frontend/src/app/api.service.ts
> +   * @description This method makes an http call and fetches data that contais information about
done

2020-09-29 14:16 UTC, peterborocz approved these changes

2020-09-29 17:42 UTC, merged